# Generated by Django 5.0.5 on 2024-05-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fone', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('tema', models.CharField(max_length=100)),
            ],
        ),
    ]
